import type { WeatherKind } from "./wmo";

export const JOKES: Record<WeatherKind | "night", string[]> = {
  sun: [
    "It compiles. The sun is out. Ship it.",
    "Warning: high UV. `sudo apply --sunscreen`.",
    "Perfect weather for `git push --force` (no it's not).",
    "Stack Overflow is up. So is the sun.",
    "`while(sunny) { code(); hydrate(); }`",
    "Zero clouds, zero excuses. Go touch grass(1).",
    "CPU throttling from heat. So is your brain.",
    "Bright enough to finally see the whiteboard bugs.",
    "`export SUNSHINE=true` — no restart required.",
    "Clear skies, clear cache, clear conscience for once.",
    "`assert weather.clouds == 0` — passes for once.",
    "Solar-powered productivity, briefly.",
  ],
  partly: [
    "50% clouds, 50% clarity. Just like your requirements.",
    "Partly cloudy — much like this legacy codebase.",
    "TODO: figure out if it's sunny or not.",
    "Schrödinger's forecast: both sunny and not, until observed.",
    "Flaky test detected: weather.status is nondeterministic.",
    "A/B testing the sky today.",
    "Merge conflict between sun.branch and cloud.branch.",
    "Race condition: cloud and sun both trying to render first.",
  ],
  cloud: [
    "Overcast. Perfect lighting for a dark theme.",
    "The cloud is down. Wait, no — it's above you.",
    "`kubectl get weather` → still cloudy.",
    "Gray sky, gray Slack, gray coffee. Balanced.",
    "100% cloud coverage, 0% cloud compute.",
    "Overcast — nature's `prefers-color-scheme: dark`.",
    "The sky's rendering a loading spinner. Please wait.",
    "Gray CI, gray sky, gray hopes for the deploy.",
  ],
  fog: [
    "Visibility low. Just like your test coverage.",
    "Fog: nature's `console.log('here')`.",
    "Can't see the deploy for the fog.",
    "`grep -r 'sun' /sky/` → no matches.",
    "Stack trace: obscured by weather.fog(dense=true).",
    "404: horizon not found.",
    "Documentation as clear as this fog.",
    "`try { see(horizon) } catch { squint() }`",
  ],
  rain: [
    "It's raining. Perfect time to `git blame`.",
    "Rain detected. Rebooting the umbrella.",
    "`npm install rain-jacket --save`.",
    "Water is falling. So is your uptime probably.",
    "It's raining bugs. And water.",
    "Precipitation: 100%. Motivation: 404.",
    "`try { walk() } catch (Rain e) { stayIndoors() }`",
    "The cloud finally pushed its changes.",
    "Umbrella.exe has stopped working.",
    "Every drop a tiny `console.log('wet')`.",
    "The forecast API returned 200 OK, you did not.",
  ],
  snow: [
    "Snow day. Merge conflicts still exist.",
    "❄ = new File(); cold.deploy();",
    "The build is frozen. Literally.",
    "Snowflake type detected. Everywhere.",
    "White screen of death, but outside.",
    "Cache invalidated by frost.",
    "Every flake unique, unlike your commit messages.",
    "`git status`: everything is white, nothing is staged.",
  ],
  thunder: [
    "Thunder detected. Unplug the servers.",
    "`throw new Storm();`",
    "Lightning strike: instant `git reset --hard`.",
    "Prod is down. Also the power.",
    "Uncaught exception: SkyException at line 0.",
    "Latency spike caused by literal lightning.",
    "The sky just force-pushed to main.",
    "Segmentation fault (core dumped by Zeus).",
  ],
  night: [
    "It's late. `commit -m 'wip'` and sleep.",
    "The sun has 404'd. Try again in 8 hours.",
    "Dark mode: engaged by nature.",
    "Night shift. The rubber duck is listening.",
    "`cron.schedule('0 3 * * *', panic)`",
    "Still awake debugging life choices.",
    "`while(true) { doomscroll(); regret(); }`",
    "The moon compiled fine. You did not.",
  ],
};

export function pickJoke(kind: WeatherKind, isNight = false): string {
  const pool = isNight ? [...JOKES.night, ...JOKES[kind]] : JOKES[kind];
  return pool[Math.floor(Math.random() * pool.length)];
}
